name: CI

on:
  push:
    branches:
      - qsw-2.0-qt6

jobs:
  linux_build:
    name: Linux Build
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get update -yq &&
        sudo apt-get install -y g++ \
                                build-essential \
                                libglu1-mesa-dev \
                                mesa-common-dev \
                                qt6-base-dev \
                                qt6-webengine-dev \
                                qt6-declarative-dev \
                                libstorm-dev \
                                libsquish-dev

    - name: qmake
      run: |
        mkdir build &&
        cd build &&
        qmake6 -o Makefile ../QSW/qsw.pro &&
        ls -la &&
        make
